import { TechnicalSupportUserTemplate } from "../constants/email-templates/technical-support-user-email.template.js";
import { TechnicalSupportTemplate } from "../constants/email-templates/technical-support.template.js";
import { SQLFunctions, Tables } from "../constants/index.js";
import { sendEmail } from "../lib/email.js";
import { logger } from "../lib/logger.js";
import { renderEmail } from "../lib/render-email.js";
import { supabase } from "../lib/supabase.js";

type CreateTechnicalRequestParams = {
  userId: string;
  organizationId: string;
  quote_id: string; // This is the UUID
  email: string;
  phone: string;
  text: string;
};

/**
 * Creates a technical support request in the database.
 */
export async function createTechnicalRequest(
  props: CreateTechnicalRequestParams,
) {
  try {
    const { data, error } = await supabase.rpc(SQLFunctions.createTechRequest, {
      p_user_id: props.userId,
      p_org_id: props.organizationId,
      p_quote_id: props.quote_id,
      p_email: props.email,
      p_phone: props.phone,
      p_text: props.text,
    });

    if (error) {
      logger.error(
        { error },
        "Error while creating technical support request RPC",
      );
      throw error;
    }

    return data;
  } catch (error) {
    logger.error({ error }, "Error in createTechnicalRequest activity");
    throw error;
  }
}

export type SendTechnicalSupportEmailsParams = {
  requestCode: string; // The autogenerated code (FRI_TS_...)
  customerEmail: string;
  customerName: string;
  customerPhone: string;
  quoteId: string; // The UUID
  quoteCode: string; // The human-readable code
};

/**
 * Sends notification emails for a technical support request.
 */
export async function sendTechnicalSupportEmails(
  props: SendTechnicalSupportEmailsParams,
) {
  try {
    // 1. Fetch Admin/Verifier Email
    const { data: configData, error: configError } = await supabase
      .from(Tables.SystemConfig)
      .select("value")
      .eq("key", "verifier_email")
      .single();

    if (configError) {
      logger.error(
        { configError },
        "Failed to fetch verifier_email from system_config",
      );
      throw configError;
    }

    const adminEmail = configData.value;

    // 2. Send Notification to Admin
    await sendNotificationToAdmin({
      adminEmail,
      customerName: props.customerName,
      customerEmail: props.customerEmail,
      customerPhone: props.customerPhone,
      quoteId: props.quoteId,
      quoteCode: props.quoteCode,
    });

    // 3. Send Acknowledgement to Customer
    await sendAcknowledgementToCustomer({
      customerEmail: props.customerEmail,
      requestCode: props.requestCode,
    });

    logger.info(
      { requestCode: props.requestCode },
      "Technical support emails sent successfully",
    );
  } catch (error) {
    logger.error({ error }, "Error in sendTechnicalSupportEmails activity");
    throw error;
  }
}

/**
 * Sends an email to the admin/verifier about the new support request.
 */
async function sendNotificationToAdmin(params: {
  adminEmail: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  quoteId: string;
  quoteCode: string;
}) {
  const mjml = TechnicalSupportTemplate(
    params.customerName,
    params.customerEmail,
    params.customerPhone,
    params.quoteId,
    params.quoteCode,
  );

  const html = renderEmail(mjml);

  return await sendEmail({
    to: params.adminEmail,
    subject: `Technical Support Requested: Quote #${params.quoteCode}`,
    html,
  });
}

/**
 * Sends an acknowledgement email to the customer with their request reference.
 */
async function sendAcknowledgementToCustomer(params: {
  customerEmail: string;
  requestCode: string;
}) {
  const mjml = TechnicalSupportUserTemplate(params.requestCode);
  const html = renderEmail(mjml);

  return await sendEmail({
    to: params.customerEmail,
    subject: "Technical Support Request Received",
    html,
  });
}
